#!/bin/bash

if command -v brew &>/dev/null; then
    echo "Homebrew installed."
else
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "Homebrew installed successfully."
    else
        echo "This script only supports macOS" >&2
        exit 1
    fi
fi


tap="viabtc/coinex"
cocoapods_version="1.11.3"
fastlane_version="2.212.1"

if ! brew tap | grep -q "^${tap}$"; then
echo "${tap} tap not found, adding it now..."
brew tap-new "${tap}"
fi

if brew search "cocoapods@${cocoapods_version}" | grep -q "cocoapods@${cocoapods_version}"; then
echo "cocoapods@${cocoapods_version} exists"
else
brew extract --version="${cocoapods_version}" cocoapods "${tap}"
fi

if brew search "fastlane@${fastlane_version}" | grep -q "fastlane@${fastlane_version}"; then
echo "fastlane@${fastlane_version} exists"
else
brew extract --version="${fastlane_version}" fastlane "${tap}"
fi

brew reinstall cocoapods@${cocoapods_version}
brew link --overwrite cocoapods@${cocoapods_version}
brew reinstall fastlane@${fastlane_version}
brew link --overwrite fastlane@${fastlane_version}