#!/bin/bash

# 检查是否已安装 Homebrew
if command -v brew &>/dev/null; then
    echo "Homebrew installed."
else
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "Homebrew installed successfully."
    else
        echo "This script only supports macOS." >&2
        exit 1
    fi
fi

# 安装 rbenv

if ! command -v rbenv > /dev/null 2>&1; then
  echo "rbenv is not installed, installing now..."
  
  brew install rbenv ruby-build
  
  # Add rbenv to PATH and initialize it
  echo '\n# 设置rbenv\neval "$(rbenv init - zsh)"' >> ~/.zshrc
  
  source ~/.zshrc
  
  echo "rbenv installed successfully."
else
  echo "rbenv is already installed."
fi


# 安装 ruby
desired_ruby_version="3.1.3"

# Check if rbenv is installed
if ! command -v rbenv > /dev/null 2>&1; then
  echo "rbenv is not installed. Please install rbenv first."
  exit 1
fi

if ! rbenv versions --bare | grep -q "^${desired_ruby_version}\$"; then
  echo "Ruby version ${desired_ruby_version} is not installed, installing now..."
  
  rbenv install "${desired_ruby_version}"
  
  echo "Ruby version ${desired_ruby_version} installed successfully."
else
  echo "Ruby version ${desired_ruby_version} is already installed."
fi

# 查看ruby安装版本
ruby -v

###### 安装bundler

# Check if bundler is installed
if ! gem list bundler -i > /dev/null; then
  echo "Bundler not installed. Installing Bundler..."
  gem install bundler
  echo "Bundler installed successfully."
else
  echo "Bundler is already installed."
fi

# Check if Gemfile exists in the current directory
if [ -f "Gemfile" ]; then
  echo "Gemfile found, installing gems using Bundler..."
  
  # Install gems listed in Gemfile using Bundler
  bundle install
  
  echo "Gems installed successfully."
else
  echo "Gemfile not found in the current directory. Please make sure you have a Gemfile in the current directory."
fi

bundle exec pod install --verbose




