name: Crowdin

on:
  delete:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  crowdin-delete:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Get branch name
        id: get_branch
        run: |
          BRANCH_NAME=${{ github.event.ref }}
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          echo "Deleted branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Crowdin delete
        uses: crowdin/github-action@v1.7.1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: false
          delete_crowdin_branch: ${{ env.BRANCH_NAME }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: GithubActionsDemo/GithubActionsDemo/zh-Hans.lproj/Localizable.strings
          translation: GithubActionsDemo/GithubActionsDemo/%osx_code%/Localizable.strings
  
  upload-on-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin Upload
        uses: crowdin/github-action@v1.7.1
        with:
          upload_sources: true
          upload_translations: false
          crowdin_branch_name: "main"
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: GithubActionsDemo/GithubActionsDemo/zh-Hans.lproj/Localizable.strings
          translation: GithubActionsDemo/GithubActionsDemo/%osx_code%/Localizable.strings

