name: Crowdin Action

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ''
    steps:
      - name: Set branch name environment variable
        run: |
          export BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Current branch is $BRANCH_NAME"
      - name: Use branch name in another step
        run: echo "Branch name is ${{ env.BRANCH_NAME }}"
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: crowdin action
      #   uses: crowdin/github-action@v1.7.1
      #   with:
      #     upload_sources: true
      #     download_translations: true
      #     source: GithubActionsDemo/GithubActionsDemo/zh-Hans.lproj/Localizable.strings
      #     translation: GithubActionsDemo/GithubActionsDemo/%osx_code%/Localizable.strings
      #     crowdin_branch_name: "${{ env.BRANCH_NAME }}"
      #     project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
      #     token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}