name: Crowdin Download

on: 
  workflow_dispatch:

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Crowdin download
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          crowdin_branch_name: ${{ env.BRANCH_NAME }}
          push_translations: true
          localization_branch_name: ${{ env.BRANCH_NAME }}
          create_pull_request: false
          # Export options
          skip_untranslated_files: true
          export_only_approved: true
          source: GithubActionsDemo/GithubActionsDemo/zh-Hans.lproj/Localizable.strings
          translation: GithubActionsDemo/GithubActionsDemo/%osx_code%/Localizable.strings
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}