name: My Workflow
on:
    workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Use branch name in another step
        run: echo "Branch name is ${{ env.BRANCH_NAME }}"
