name: Install dependencies

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script
      run: |
        chmod +x InstallDependencies
        ./InstallDependencies
