name: Localized Strings

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x LocalizeAll

    - name: Run script
      run: ./LocalizeAll

    - name: Commit changes
        run: |
          git config --global user.name "JJ"
          git config --global user.email "JJ@example.com"
          git add .
          git commit -m "Automated commit"
          git push
