name: Localized Strings

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x LocalizeAll

    - name: Run script
      run: ./LocalizeAll
