name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      success_message_title:
        required: false
        type: string
      failure_message_title:
          required: false
          type: string
      pr_html_url:
        required: false
        type: string
      pr_number:
        required: false
        type: string
      pr_title:
        required: false
        type: string
      pr_body:
        required: false
        type: string
      base_sha:
        required: false
        type: string
      head_sha:
        required: false
        type: string

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_MOBILE_WEBHOOK }}
        STATUS: ${{ inputs.status }}
        SUCCESS_MESSAGE_TITLE: ${{ inputs.success_message_title }}
        FAILURE_MESSAGE_TITLE: ${{ inputs.failure_message_title }}
        PR_HTML_URL: ${{ inputs.pr_html_url }}
        PR_NUMBER: ${{ inputs.pr_number }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        PR_BASE_SHA: ${{ inputs.base_sha }}
        PR_HEAD_SHA: ${{ inputs.head_sha }}
      run: |
        # 根据STATUS确定消息内容
        if [ "$STATUS" == "success" ]; then

          # 获取Body
          escaped_pr_body="${PR_BODY//$'\n'/\\n}"
          if [ -z "$escaped_pr_body" ]; then
            escaped_pr_body="未填写⭕"
          fi
          escaped_pr_body="*Description:*\n$escaped_pr_body"

          # 获取提交信息
          commits=$(git log --pretty=format:"%H - %s (%an)" "$PR_BASE_SHA..$PR_HEAD_SHA")
          # 提取每个提交的哈希和消息，并构建链接
          formatted_commits=""
          while read -r line; do
            commit_hash=$(echo "$line" | awk '{print $1}')
            commit_message=$(echo "$line" | awk '{$1=""; print $0}')
            commit_url="$PR_HTML_URL/commits/$commit_hash"
            formatted_commit="<$commit_url|${commit_message}>"
            formatted_commits="${formatted_commits}${formatted_commit}\n"
          done <<< "$commits"
          formatted_commits="*Commits:*\n$formatted_commits"

          curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK <<CURL_DATA
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "$SLACK_MESSAGE_TITLE",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "点击按钮进行下载"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "下载",
                    "emoji": true
                  },
                  "url": "http://3.33.146.9:5000/",
                  "style": "primary"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<$PR_HTML_URL|#$PR_NUMBER $PR_TITLE>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$escaped_pr_body"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$formatted_commits"
                }
              }
            ]
          }
          CURL_DATA
        elif [ "$STATUS" == "failure" ]; then
          curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK <<CURL_DATA
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "$FAILURE_MESSAGE_TITLE",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "点击按钮查看运行错误"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "查看",
                    "emoji": true
                  },
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "style": "danger"
                }
              }
            ]
          }
          CURL_DATA
        fi
