name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string

jobs:
  notify-slack:
    runs-on: macOS-latest
    steps:
    - name: Notify Slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_MOBILE_WEBHOOK }}
        STATUS: ${{ inputs.status }}
      run: |
        echo "Sending notification with input: $STATUS"
        echo "Sending notification with input: ${{ github.event.pull_request.html_url }}"
        